### ISSUE TITLE
Debug mode issue

### ISSUE THREAD

**Issue by zhanang19** [RoyVoetman/flysystem-gitlab-storage#3]
I think I was got an issue when checking a file is exists with debug mode enabled.

My case:
Trying to upload a file in Laravel with my own package https://github.com/zhanang19/medialibrary-gitlab-storage but always failed. Trying to see in the log file, it's was fail on `has` method.

![Log File](https://user-images.githubusercontent.com/19884603/81163274-af898080-8fb8-11ea-8bfb-763caab5cf85.png)

I think this GuzzleException in `has` method must be never catching because it's always returning an error 404 not found when the file is not found.
 https://github.com/RoyVoetman/flysystem-gitlab-storage/blob/999c418e234389f02d31a8c10a09be377eea777a/src/GitlabAdapter.php#L239 

Sorry for my bad English cause I am not fluent in English. Thanks in advance.

**Comment by RoyVoetman** [comment]
This is expected behavior, the debug mode is meant to be able to look into the underlying Guzzle Exceptions (i.e. the response from the gitlab api). 

As you have shown the exception is catched, but if you look at the underlying `failed()` method, it will either throw the exception or `return false` based on the debug mode option. 

The conclusion is that you should not use debug mode when trying to check if a file exists. You should only use this mode if you are interested in what exception was actually thrown by Guzzle.

```php
    /**
     * @param  \Exception  $e
     * @param  bool  $return
     *
     * @return mixed
     * @throws \Exception
     */
    public function failed(\Exception $e, $return = false)
    {
        if ($this->isDebugEnabled()) {
            throw $e;
        }
        
        return $return;
    }
```
