### ISSUE TITLE
Plan for flysystem 2.x

### ISSUE THREAD

**Issue by ElGigi** [RoyVoetman/flysystem-gitlab-storage#5]
Hi,

Do you have a plan to upgrade your library for flysystem version 2.x ?

Regards.

**Comment by RoyVoetman** [comment]
Hi,

I just looked at the V2 conversion guide and it doesn’t seem too complicated to migrate to V2.

I simply haven’t gotten around to it yet. This weekend, if I can find some spare time, I will try to add support for V2.

**Comment by ElGigi** [comment]
Nice! Thanks

**Comment by RoyVoetman** [comment]
Since fly-system v2 is still under beta I starting the migration to v2 in a separate branch.
https://github.com/RoyVoetman/flysystem-gitlab-storage/tree/2.x

Unfortunately, I wasn't able to fully migrate everything to version 2 due to the new way v2 expects exceptions to be thrown and how file-metadata should be returned. However, since version 2 is still in a beta phase I foresee no immediate need to implement version 2 as fast as possible.

**Comment by RoyVoetman** [comment]
Everything is now migrated to v2 in the branch 2.x, except for deleting directories, retrieving file size, and retrieving an iterator for the list of contents.

I estimate that the remaining points will be implemented next weekend

**Comment by ElGigi** [comment]
Nice, I will test soon as possible to make you a feedback.

**Comment by RoyVoetman** [comment]
https://github.com/RoyVoetman/flysystem-gitlab-storage/releases/tag/v2.0.0
